{
 "title": "Data Reliability Perf Dash",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Currency Freshness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, code) (rate(app_checkout_currency_freshness_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Currency Completeness",
   "type": "timeseries",
   "description": "This shows how much data we currently have available for currency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "app_checkout_currency_completeness_gauge"
    }
   ]
  },
  {
   "title": "Order Completeness Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status) (increase(app_checkout_order_complete[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}