version: "prometheus/v1"
service: "currency"
slos:
  - name: "currency-completeness" # Format: <object>-<sli-type>
    objective: 99
    sli:
      events:
        error_query: sum(rate(app_checkout_currency_completeness_gauge{status="incomplete"}[{{.window}}]))
        total_query: sum(rate(app_checkout_currency_completeness_gauge{status="complete"}[{{.window}}]))
    alerting:
      page_alert:
        disable: true
      ticket_alert:
        disable: true
