name: build-first-party-nginx-otel-module
run-name: ${{ github.actor }} is triggering pipeline
on:
  workflow_dispatch:
  pull_request:
env:
  NGINX_VERSION: release-1.24.0
  GRPC_CPP_SHA: a3f10052090539cd3e19aa8e04f3bf8eceae2964
  GRPC_CPP_VERSION: v1.52.0
  OTEL_CPP_SHA: d56a5c702fc2154ef82400df4801cd511ffb63ea
  OTEL_CPP_VERSION: v1.8.2

jobs:
  build-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nginxinc/nginx-otel repository
        uses: actions/checkout@v3
        with:
          repository: nginxinc/nginx-otel
#          ref: $NGINX_VERSION
          path: nginx-otel
      - name: Checkout nginx/nginx repository
        uses: actions/checkout@v3
        with:
          repository: nginx/nginx
#          ref: $NGINX_VERSION
          ref: 'release-1.24.0'
          path: nginx
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ca-certificates \
            cmake \
            curl \
            git \
            gnupg1 \
            libc-ares-dev \
            libre2-dev \
            libpcre3-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libsystemd-dev \
            pkg-config \
            zlib1g-dev
      - name: Configure nginx
        working-directory: nginx
        run: auto/configure --with-compat
      - name: Build module
        working-directory: nginx-otel
        run: |
          sed -i 's/18dda3c586b2607d8daead6b97922e59d867bb7d # v1.46.6/a3f10052090539cd3e19aa8e04f3bf8eceae2964 # v1.52.0/g' CMakeLists.txt \
          && sed -i 's/57bf8c2b0e85215a61602f559522d08caa4d2fb8 # v1.8.1/d56a5c702fc2154ef82400df4801cd511ffb63ea # v1.8.2/g' CMakeLists.txt
          mkdir -p build && cd build
          cmake -DNGX_OTEL_NGINX_BUILD_DIR=${PWD}/../../nginx/objs ..
          make -j 4
          strip ngx_otel_module.so
      - name: Archive module
        uses: actions/upload-artifact@v3
        with:
          name: nginx-otel-module
          path: nginx-otel/build/ngx_otel_module.so
      - name: Archive protoc and opentelemetry-proto
        uses: actions/upload-artifact@v3
        with:
          name: protoc-opentelemetry-proto
          path: |
            nginx-otel/build/_deps/grpc-build/third_party/protobuf/protoc
            nginx-otel/build/_deps/otelcpp-src/third_party/opentelemetry-proto